### ISSUE TITLE
Can this approach be applied to two-stage models, such as Fast RCNN - FPN

### ISSUE THREAD

**Issue by XcodeHw** [fpv-iplab/DA-RetinaNet#1]

**Comment by GiovanniPasq** [comment]
Hi, we think you can apply this approach on faster rcnn with fpn. We also beleave that you can implement it easly following our implementation (see the discriminators classes inside the retinanet.py and what the forward method return inside the fpn.py). I suggest you to implement this architecture using detectron 0.2.1 because should be more easy to customize standard object detector.
